# https://github.com/sasstools/sass-lint/blob/master/docs/sass-lint.yml
# https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml

options:
  formatter: stylish

rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2

  # Mixins
  mixins-before-declarations:
    - 2
    - exclude: [
      'mq',
      'breakpoint',
      'break-max-mobile',
      'break-tablet',
      'break-max-tablet',
      'break-desktop'
    ]

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-color-literals:
    - 2
    - allow-rgba: true
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-vendor-prefixes:
    - 2
    - additional-identifiers: []
      excluded-identifiers: [ms, webkit]
  no-warn: 0
  placeholder-in-extend: 2
  property-units: 2

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  nesting-depth:
    - 2
    - max-depth: 5

  # Name Formats
  class-name-format:
    - 2
    - convention: "[a-z0-9\\-\\_]+"
  function-name-format: 2
  id-name-format:
    - 2
    - convention: "[a-z0-9\\-\\_]+"
  mixin-name-format: 2
  placeholder-name-format: 2
  variable-name-format: 2

  # Style Guide
  attribute-quotes: 2
  border-zero: 0
  brace-style:
    - 2
    - allow-single-line: false
  empty-args: 2
  hex-notation: 0
  indentation:
    - 2
    - size: 2
  leading-zero: 2
  pseudo-element: 2
  property-sort-order: 0
  quotes: 2
  shorthand-values: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  final-newline: 2
